name: ablaevent_flutter
description: Flutter implementation of Ablaevent client for iOS, Android and Web
version: 3.1.1
homepage: https://e.abla.io
repository: https://github.com/AblaAnalytics/ablaevent-flutter
issue_tracker: https://github.com/AblaAnalytics/ablaevent-flutter/issues
documentation: https://github.com/AblaAnalytics/ablaevent-flutter#readme

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.ablaevent.ablaevent_flutter
        pluginClass: AblaeventFlutterPlugin
      ios:
        pluginClass: AblaeventFlutterPlugin
      web:
        pluginClass: AblaeventWeb
        fileName: src/ablaevent_web.dart
